#!/bin/bash

if [ ${#1} -eq 0 ]; then
    echo "usage: dapprog file"
    exit 0
fi


CURRENT_DIR=$(cd $(dirname $0); pwd)

IMAGE_FILE=$1

EXT="${IMAGE_FILE##*.}"
echo EXT: $EXT

#flash write_image erase xxx.hex;
#flash write_image erase xxx.bin 0x08000000;

if [ "${EXT}" == "svf" ]; then
    TARGET="$IMAGE_FILE"
elif [ "${EXT}" == "bit" ]; then
    echo "illegal suffix [$EXT]"
    exit 1
else
    echo "illegal suffix [$EXT]"
    exit 1
fi

CONFIG=${CURRENT_DIR}/cmsisdap.cfg

sudo openocd -f ${CONFIG} -c \
"   init;
    scan_chain;
    svf -tap ecp5.tap -quiet -progress ${TARGET};
    exit;
"

exit $?


